name: Run Uzum API Script

on:
  workflow_dispatch:  # qo'lda ishga tushirish uchun
  schedule:
    - cron: '*/15 * * * *'  # har 15 daqiqada ishga tushadi

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repozitoriyani yuklash
        uses: actions/checkout@v3

      - name: Python 3.9 ni sozlash
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutubxonalarni o'rnatish
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Google service_account.json faylini yaratish
        run: |
          echo '${{ secrets.GSHEET_CREDENTIALS }}' > service_account.json

      - name: Python kodni ishga tushurish
        run: python main.py
